version: 0.0

os: linux

files:
  files:
  - source: dist/my-angular-project
    destination: /var/www/my-angular-project
  - source: deploy-scripts/application-start-hook.sh   # Add this
    destination: /opt/codedeploy-agent/deployment-root/ # Ensure correct path


permissions:
  - object: /var/www/my-angular-project
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300
      runas: ec2-user  # Ensure the correct user runs the script

